GET http://localhost:3000/bank-accounts

@bank_account_id=1c22526d-5260-456f-a157-4b48790657e3
###
GET http://localhost:3000/bank-accounts/{{bank_account_id}}


###
POST http://localhost:3000/bank-accounts
Content-Type: application/json

{
  "account_number": "1111-111",
  "owner_name": "John Doe"
}


###
POST http://localhost:3000/bank-accounts/{{bank_account_id}}/pix-keys
Content-Type: application/json

{
  "key": "t@email.com",
  "kind": "email"
}


###
GET http://localhost:3000/bank-accounts/{{bank_account_id}}/pix-keys


###
POST http://localhost:3000/bank-accounts/{{bank_account_id}}/transactions
Content-Type: application/json

{
  "pix_key_key": "0000",
  "pix_key_kind": "cpf",
  "description": "My transaction",
  "amount": 10.00
}


###
GET http://localhost:3000/bank-accounts/{{bank_account_id}}/transactions
