version: '3'

services:
  app:
    container_name: app_nestjs_code_pix
    build: .
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
  db:
    image: postgres:13-alpine
    restart: always
    tty: true
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - .docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
